/**
 * IMPOSTER – Holiday Edition
 * Word Lists
 */

const WORD_LISTS = {
  weihnachten: [
    "Tannenbaum",
    "Schneemann",
    "Geschenk", 
    "Christkind",
    "Lebkuchen",
    "Weihnachtsmarkt",
    "Glühwein",
    "Adventskranz",
    "Nikolaus",
    "Schlitten",
    "Rentier",
    "Kerze",
    "Glocke",
    "Stern",
    "Krippe",
    "Engel",
    "Mistelzweig",
    "Plätzchen",
    "Stollen",
    "Lichterkette",
    "Kamin",
    "Socken",
    "Schneeflocke",
    "Punsch",
    "Marzipan",
    "Zimt",
    "Nussknacker",
    "Wunschzettel",
    "Bescherung",
    "Heiligabend",
    "Räuchermännchen",
    "Christbaumkugel",
    "Lametta",
    "Spekulatius",
    "Dominosteine",
    "Bratapfel",
    "Weihnachtslied",
    "Schornstein",
    "Puderzucker",
    "Vanillekipferl"
  ],
  
  noser: [
    "Dani",
    "Nico",
    "zino",
    "David",
    "Edu",
    "Lionel",
    "Amina",
    "Diego",
    "Marina",
    "Margarita",
    "Noe",
    "Kaylee",
    "Filip G.",
    "Filip K.",
    "Dario",
    "Julian",
    "Samih",
    "Kaylin",
    "Milana",
    "Tea",
    "Franco",
    "Sujan",
    "Andrew",
    "Phuc",
    "Nadine",
    "Laura",
    "Damian",
    "Marco",
    "Julia",
    "Levin"
  ],
  
  orte: [
    "Strand",
    "Berg",
    "Wald",
    "See",
    "Fluss",
    "Stadt",
    "Dorf",
    "Park",
    "Zoo",
    "Museum",
    "Kino",
    "Theater",
    "Restaurant",
    "Café",
    "Supermarkt",
    "Schule",
    "Universität",
    "Krankenhaus",
    "Apotheke",
    "Bank",
    "Post",
    "Bahnhof",
    "Flughafen",
    "Hotel",
    "Schwimmbad",
    "Fitnessstudio",
    "Bibliothek",
    "Kirche",
    "Rathaus",
    "Spielplatz",
    "Friedhof",
    "Bauernhof",
    "Fabrik",
    "Büro",
    "Werkstatt",
    "Tankstelle",
    "Friseur",
    "Bäckerei",
    "Metzgerei",
    "Blumenladen"
  ],
  
  alltag: [
    "Handy",
    "Computer",
    "Fernseher",
    "Kühlschrank",
    "Waschmaschine",
    "Staubsauger",
    "Bett",
    "Stuhl",
    "Tisch",
    "Sofa",
    "Lampe",
    "Spiegel",
    "Uhr",
    "Schlüssel",
    "Brille",
    "Tasche",
    "Schuhe",
    "Jacke",
    "Hose",
    "Hemd",
    "Socken",
    "Mütze",
    "Regenschirm",
    "Zahnbürste",
    "Handtuch",
    "Seife",
    "Shampoo",
    "Buch",
    "Zeitung",
    "Stift",
    "Papier",
    "Schere",
    "Kleber",
    "Tasse",
    "Teller",
    "Gabel",
    "Messer",
    "Löffel",
    "Topf",
    "Pfanne"
  ]
};


function getRandomWord(category) {
  if (category === 'random') {
    const categories = Object.keys(WORD_LISTS);
    category = categories[Math.floor(Math.random() * categories.length)];
  }
  
  const words = WORD_LISTS[category] || WORD_LISTS.weihnachten;
  return words[Math.floor(Math.random() * words.length)];
}

// Export for use in game.js
window.WORD_LISTS = WORD_LISTS;
window.getRandomWord = getRandomWord;
